### ISSUE TITLE
why there are addtional opensfit routes when I create one pass-through route

### ISSUE THREAD

**Issue by barryzhounb** [Maistra/ior#13]
I am working on OpenShift routes. A TLS traffic will go through Routes and Istio, then go to my service. 

Route's destination service is Istio ingress-gateway service, it exposes port 9999. And Routes will pass through TLS traffic, and tls traffic will be terminated in Istio Gateway.

The following is my deployment yaml:

```
apiVersion: v1
kind: Service
metadata:
  name: simplewebserver-istio-ingressgateway
  namespace: istio-system
  labels:
    app: simplewebserver-istio-ingressgateway
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: simplewebserver-ingress-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 9999
      name: tls
      protocol: TLS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "*"
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: simplewebserver-istio-ingressgateway-route
  namespace: istio-system
  labels:
    app: simplewebserver-istio-ingressgateway
spec:
  host: www.https.com
  to:
    kind: Service
    name: simplewebserver-istio-ingressgateway
    weight: 100
  port:
    targetPort: 9999
  tls:
    termination: passthrough
```

After deploy the above yaml, then I got the following routes. I expect I will get one route - simplewebserver-istio-ingressgateway-route, but in fact there are two routes, I think it is an issue, why another route mynamespace-simplewebserver-ingress-gateway-98tlj has been created? What is it for?

```
mynamespace-simplewebserver-ingress-gateway-98tlj   mynamespace-simplewebserver-ingress-gateway-98tlj-istio-system.apps.devospreycluster.os.fyre.ibm.com             istio-ingressgateway                   https     passthrough          None
simplewebserver-istio-ingressgateway-route          www.https.com                                                                                                    simplewebserver-istio-ingressgateway   9999      passthrough          None

```
If my Gateway has two hosts that looks like this

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: simplewebserver-ingress-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 9999
      name: tls
      protocol: TLS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    hosts:
    - "a.b.c"
    - "e.f.h"
```

Then I got another additional routes:

```
NAME                                                HOST/PORT                                                                                              PATH      SERVICES                               PORT      TERMINATION
mynamespace-simplewebserver-ingress-gateway-f2rqv   a.b.c                                                                               istio-ingressgateway                   https     passthrough          None
mynamespace-simplewebserver-ingress-gateway-phrvl   e.f.h                                                                               istio-ingressgateway                   https     passthrough          None
```

Obviously, these additional routes have been added by Istio Gateway automatically. So, my question is, I expect one route that I want to create, why it generate more additional routes by OpenShift Route and Istio Gateway? Is there any yaml file wrong or missing? How to check it or fix this issue?
